### ISSUE TITLE
Small bug in Dialog.prompt out of nativeCocoon (fix inc.)

### ISSUE THREAD

**Issue by JiDW** [ludei/cocoonjs-plugins#13]
Line 113 of https://github.com/ludei/cocoonjs-plugins/blob/master/src/device/cocoon_dialog.js

properties isn't filled with call parameters

It should use "args" instead.

var result = prompt(args[0], args[1]);

It's a small bug but it's useful for testing outside of cocoon.

**Comment by LibelulaV** [comment]
Hello, 

Thanks for the bug report. I will have a look at it right now. 

Regards.

**Comment by JiDW** [comment]
Thanks :)
